---
services:
  # ---------------------------------------------
  # Setup docker-volume-backup
  #
  # https://hub.docker.com/r/offen/docker-volume-backup
  # ---------------------------------------------
  docker-volume-backup:
    #image:          offen/docker-volume-backup:v2.43.0
    #image:          offen/docker-volume-backup:v2.43.4
    #image:          offen/docker-volume-backup:v2.47.0
    #image:          offen/docker-volume-backup:v2.48.2
    image:          offen/docker-volume-backup:v2.49.0
    container_name: docker-volume-backup
    restart:        unless-stopped

    security_opt:
      - no-new-privileges:true

    networks:
      - docker-volume-backup-net

    environment:
      
      # Container timezone setting; enforces required ENV_TZ from host/environment
      - TZ=${ENV_TZ:?err}

      # Random delay (up to 1 minute) added before scheduled jobs to prevent execution overlap
      - BACKUP_JITTER=1m

      # Greedy exclusion of the folder /backup/my-app-backup/backup
      # Use https://regex101.com/ with Goland to derive expression
      - BACKUP_EXCLUDE_REGEXP=\/backup\/my-app-backup\/docker-homelab\/docker\/docker-volume-backup\/data\/host\/backups\/.*$

      # Include hostname in backup file name
      - BACKUP_FILENAME=$ENV_HOSTNAME-backup-%Y-%m-%dT%H-%M-%S.tar.gz

      # Notifications (email, Slack, etc.) can be sent out when a backup run finishes.
      # Configuration is provided as a comma-separated list of URLs as consumed
      # by `shoutrrr`: https://containrrr.dev/shoutrrr/v0.5/services/overview/
      # The content of such notifications can be customized. Dedicated documentation
      # on how to do this can be found in the README. When providing multiple URLs or
      # an URL that contains a comma, the values can be URL encoded to avoid ambiguities.
      # The below URL demonstrates how to send an email using the provided SMTP
      # configuration and credentials.
      - NOTIFICATION_URLS=smtp://${ENV_DOCKER_VOLUME_BACKUP_GMAIL_EMAIL:?gmail email required}:${ENV_DOCKER_VOLUME_BACKUP_GMAIL_APP_PASSWORD:?gmail app password required}@smtp.gmail.com:587/?fromAddress=${ENV_DOCKER_VOLUME_BACKUP_GMAIL_EMAIL:?gmail email required}&toAddresses=${ENV_DOCKER_VOLUME_BACKUP_EMAIL_TO:?email to required}

      # By default, notifications would only be sent out when a backup run fails
      # To receive notifications for every run, set `NOTIFICATION_LEVEL` to `info`
      # instead of the default `error`.
      # Set to info so manually calling backup also sends mail.
      - NOTIFICATION_LEVEL=info

      # Custom variables passed into the container for /scripts/post-prune.sh execution

      # Retention policy: Number of recent local .tar.gz archives to retain in /archive
      - ENV_DOCKER_VOLUME_BACKUP_KEEP_LAST_BACKUPS=7

      # ASUSTOR NAS Rsync daemon connection details (Port 873)
      #   ENV_RSYNC_SYNC_NAS_HOST must be IP so it can be resolved by targets without local resolution (i.e. dns-001)
      - ENV_RSYNC_SYNC_NAS_HOST=${ENV_NAS_BACKUP_TARGET}
      - ENV_RSYNC_SYNC_NAS_USER=${ENV_DOCKER_VOLUME_BACKUP_RSYNC_SYNC_NAS_USER}
      - ENV_RSYNC_SYNC_NAS_PASSWORD=${ENV_DOCKER_VOLUME_BACKUP_RSYNC_SYNC_NAS_PASSWORD}
      - ENV_RSYNC_SYNC_NAS_MODULE=${ENV_DOCKER_VOLUME_BACKUP_RSYNC_SYNC_NAS_MODULE}

      # Node identifier used to create host-specific backup subdirectories on the NAS
      - ENV_RSYNC_SYNC_HOSTNAME=${ENV_HOSTNAME}

    # Uncomment both lines to immediately trigger a single backup
    #restart:    "no"
    #entrypoint: backup

    volumes:
      # Backup data
      - /srv:/backup/my-app-backup:ro
      
      # Mounting the Docker socket allows the script to stop and restart
      # the container during backup. You can omit this if you don't want
      # to stop the container
      - /var/run/docker.sock:/var/run/docker.sock:ro

      # If you mount a local directory or volume to `/archive` a local
      # copy of the backup will be stored there. You can override the
      # location inside of the container by setting `BACKUP_ARCHIVE`.
      # You can omit this if you do not want to keep local backups.
      - ./data/host/backups:/archive

      # Multiple backup schedules
      - ./data/common/conf.d:/etc/dockervolumebackup/conf.d

      # Custom notifications
      - ./data/common/notifications.d:/etc/dockervolumebackup/notifications.d

      # Mount the external post-prune script as read-only into the container
      - ./data/common/scripts/post-prune.sh:/scripts/post-prune.sh:ro

    labels:
      # Executes at the end of the backup lifecycle after containers are restarted and online
      docker-volume-backup.prune-post: "sh /scripts/post-prune.sh"

networks:
  docker-volume-backup-net:
    name: docker-volume-backup-net
    driver: bridge
