---
services:
  # ---------------------------------------------
  # Setup spoolman
  #
  # Note this container has a locked 1000:1000 permissions
  #
  # https://github.com/Donkie/Spoolman
  # ---------------------------------------------
  
  spoolman:
    #image:          ghcr.io/donkie/spoolman:0.23.1
    image:          ghcr.io/donkie/spoolman:0.26.1
    container_name: spoolman
    restart:        unless-stopped

    networks:
      - frontend

    ports:
      - "7912:8000"

    environment:
      TZ: ${ENV_TZ:?err}      

    volumes:
      - ./data/host/spoolman:/home/app/.local/share/spoolman

networks:
  frontend:
