---

services:
  roblox-nextgen:
    image:          nginx:1.31.6-alpine
    container_name: roblox-nextgen
    restart:        unless-stopped

    networks:
      - roblox-nextgen-net

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./data/common/html:/usr/share/nginx/html:ro
      - ./data/common/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/host/certs:/etc/nginx/certs:ro

networks:
  roblox-nextgen-net:
    name: roblox-nextgen-net
    driver: bridge
