---
services:
  # ---------------------------------------------
  # Setup semaphoreui
  #
  # semaphore - https://hub.docker.com/r/semaphoreui/semaphore
  # mysql was changed to sqlite for simplicity in this container
  #
  # Alpine (for permission fixer)
  #   https://hub.docker.com/_/alpine
  # ---------------------------------------------
  permissions-fixer:
    image:          alpine:3.24.1
    container_name: semaphoreui-permissions-fixer
    network_mode:   none
    volumes:
      - ./data/host/semaphoreui/config:/semaphoreui/config
      - ./data/host/semaphoreui/data:/semaphoreui/data
      - ./data/host/semaphoreui/keys:/semaphoreui/keys
      - ./data/host/semaphoreui/tmp:/semaphoreui/tmp
    # Run the chown (1001:root) command on all 4 directories and exit (no -R)
    command: chown 1001:root /semaphoreui/config /semaphoreui/data /semaphoreui/keys /semaphoreui/tmp

  semaphoreui:
    image:          semaphoreui/semaphore:v2.19.8
    container_name: semaphoreui
    restart:        unless-stopped

    depends_on:
      permissions-fixer:
        condition: service_completed_successfully

    networks:
      frontend: 

    ports:
      - target: 3000
        published: 3000
        protocol: tcp

    environment:
      SEMAPHORE_DB_DIALECT: sqlite 
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${ENV_SEMAPHOREUI_ADMIN_PASSWORD:?err}
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      ANSIBLE_HOST_KEY_CHECKING: false  # (optional) change to true if you want to enable host key checking
      SEMAPHORE_SCHEDULE_TIMEZONE: ${ENV_TZ:?err} # Set the timezone for scheduling tasks

    volumes:
      # semaphore specific volumes
      - ./data/host/semaphoreui/data:/var/lib/semaphore:rw
      - ./data/host/semaphoreui/config:/etc/semaphore:rw
      - ./data/host/semaphoreui/tmp:/tmp/semaphore:rw

      # ansible repo
      - /srv/ansible-homelab:/srv/ansible-homelab:ro

      # ansible keys
      - ./data/host/semaphoreui/keys:/srv/ansible-keys:ro
 
networks:
  frontend:
