---
services:
  # ---------------------------------------------
  # Setup infisical
  #
  # postgres - https://hub.docker.com/_/postgres
  # redis - https://hub.docker.com/_/redis
  # infisical - https://hub.docker.com/r/infisical/infisical
  # 
  # Recomendations for package versions:
  #  https://infisical.com/docs/self-hosting/deployment-options/native/linux-package/installation
  #  As at 25-March-2026 - PostgreSQL v14 and up, Redis V6.x or 7.x
  #
  # Database migration steps for postgres 18 and beyond:
  #  https://medepros.ca/blog/upgrading-to-postgresql-18-in-docker-a-crucial-change-you-need-to-be-aware-of/
  #
  # ---------------------------------------------

  backend:
    image:          infisical/infisical:${ENV_INFISICAL_TAG:-v0.77.0-postgres}
    container_name: infisical-backend
    restart:        unless-stopped

    networks:
      backend:
      frontend:

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

    ports:
      - 80:8080

    environment:
      NODE_ENV: production
      DB_CONNECTION_URI: postgres://${ENV_POSTGRES_USER}:${ENV_POSTGRES_PASSWORD}@postgres:5432/${ENV_POSTGRES_DB}
      REDIS_URL: redis://redis:6379
      SITE_URL: http://${ENV_HOST:?hostname required}:80
      ENCRYPTION_KEY: ${ENV_ENCRYPTION_KEY:?encryption key required}
      AUTH_SECRET: ${ENV_AUTH_SECRET:?auth secret required}

      SMTP_HOST: ${ENV_INFISICAL_EMAIL_HOST:?email host required}
      SMTP_USERNAME: ${ENV_INFISICAL_EMAIL_USERNAME:?email username required}
      SMTP_PASSWORD: ${ENV_INFISICAL_EMAIL_PASSWORD:?email username required}
      SMTP_PORT: ${ENV_INFISICAL_EMAIL_PORT:?email port required}
      SMTP_FROM_ADDRESS: ${ENV_INFISICAL_EMAIL_FROM:?email from address required}
      SMTP_FROM_NAME: ${ENV_INFISICAL_EMAIL_NAME:?email name required}

  redis:
    #image:          docker.io/library/redis:7.2.5-alpine3.20
    image:          docker.io/library/redis:7.4.8-alpine3.21
    container_name: infisical-redis
    restart:        unless-stopped

    networks:
      backend:
      frontend:

    ports:
     - 6379:6379

    environment:
      ALLOW_EMPTY_PASSWORD: yes

    command: --save 60 1 --loglevel warning

    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    
    volumes:
      - ./data/host/redis:/data # no :Z as it is strictly not shared between containers

  postgres:
    #image:          docker.io/library/postgres:14-alpine
    image:          docker.io/library/postgres:18.3-alpine3.23
    container_name: infisical-postgres
    restart:        unless-stopped

    networks:
      backend:

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s

    environment:
      POSTGRES_USER: ${ENV_POSTGRES_USER:?database username required}
      POSTGRES_PASSWORD: ${ENV_POSTGRES_PASSWORD:?database password required}
      POSTGRES_DB: ${ENV_POSTGRES_DB:?database name required}
      # Remove for new handling in V18
      #PGDATA: /var/lib/postgresql/data/infisical

    volumes:
      - ./data/host/db-data:/var/lib/postgresql # no :Z as it is strictly not shared between containers

networks:
  backend:
    internal: true
  frontend:
