services:

  # ---------------------------------------------
  # Setup uptime-kuma
  #
  # https://hub.docker.com/r/louislam/uptime-kuma
  # ---------------------------------------------
  uptime-kuma:
    image:          louislam/uptime-kuma:2.5.0

    container_name: uptime-kuma
    restart:        unless-stopped
    
    networks:
      - frontend

    ports:
      # <Host Port>:<Container Port>
      - "3001:3001"

    volumes:
      - ./data/host:/app/data
      
    security_opt:
      - no-new-privileges:true

    environment:
      - ENV_TZ=${ENV_TZ:?err}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  frontend:
