---
services:
  # ---------------------------------------------
  # Setup speedtest-tracker
  #
  # speedtest-tracker - https://docs.linuxserver.io/images/docker-speedtest-tracker/
  #                     https://github.com/alexjustesen/speedtest-tracker/releases
  # ---------------------------------------------
  speedtest-tracker:
    image:          lscr.io/linuxserver/speedtest-tracker:1.15.0
    container_name: speedtest-tracker
    restart:        unless-stopped

    networks:
      - speedtest-tracker-net

    ports:
      - '8080:80'

    environment:
      PUID: ${ENV_DOCKER_UID:?err}
      PGID: ${ENV_DOCKER_GID:?err}
      TZ: ${ENV_TZ:?err}
      DISPLAY_TIMEZONE: ${ENV_TZ:?err}

      ADMIN_NAME: ${ENV_SPEEDTEST_TRACKER_ADMIN_NAME:?err}          # NOTE: Only effective during initial setup.
      ADMIN_EMAIL: ${ENV_SPEEDTEST_TRACKER_ADMIN_EMAIL:?err}        # NOTE: Only effective during initial setup.
      ADMIN_PASSWORD: ${ENV_SPEEDTEST_TRACKER_ADMIN_PASSWORD:?err}  # NOTE: Only effective during initial setup.

      APP_KEY: ${ENV_SPEEDTEST_TRACKER_APP_KEY:?err}
      APP_URL: http://tools-001.mgmt.gregrob.net:8080
      DB_CONNECTION: sqlite
      SPEEDTEST_SCHEDULE: 15 * * * * # Run at 15min past every hour
      #SPEEDTEST_SERVERS: 14670, 12491 # Aussie Broadband, Telstra - generate with docker run -it --rm --entrypoint /bin/bash lscr.io/linuxserver/speedtest-tracker:latest list-servers

    volumes:
      - ./data/host/config:/config

networks:
  speedtest-tracker-net:
    name: speedtest-tracker-net
    driver: bridge
